[package]
name = "pong"
version = "0.1.0"
authors = ["chapmasore"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.0-rc.0"
imgui = "0.0.23"